version: '3.8'

services:
    mysql:
        image: mysql:5.7
        container_name: mysql-container
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: admin
          MYSQL_PASSWORD: admin
        ports:
          - "3306:3306"
        volumes:
          - mysql_data:/var/lib/mysql
        networks:
          - backend-network  
    api-gateway:
        image: api-gateway:latest
        ports:
          - "8000:8000"
        environment:
          EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka
        depends_on:
          - discovery-server
        networks:
          - backend-network
    discovery-server:
        image: discovery-server:latest
        ports:
          - "8761:8761"
        networks:
          - backend-network
    security-service:
        image: security-service:latest
        ports:
          - "8085:8085"
        environment:
          EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka
        depends_on:
          - discovery-server
          - mysql
        networks:
          - backend-network
    news-service:
        image: news-service:latest
        ports:
          - "8080:8080"
        environment:
          EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka
        depends_on:
          - discovery-server
          - mysql
        networks:
          - backend-network
    mail-service:
        image: mail-service:latest
        ports:
          - "8081:8081"
        environment:
          EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka
        depends_on:
          - discovery-server
          - mysql
        networks:
          - backend-network
volumes:
  mysql_data:
    driver: local
networks:
  backend-network:
    driver: bridge