apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: mysub
spec:
  topic: mytopic
  route: /pubsub/subscribe/mytopic
  pubsubname: pubsub
scopes:
  - combinedapp  # Ensure this matches your app-id