server:
  port: 8081
spring:
  application:
    name: mail-service
  mail:
   host: smtp.mailtrap.io
   port: 25
   username: 3f4219b0fb747f
   password: e13c1b825a241c
eureka:
  client:
    instance:
      preferIpAddress: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/